Repository boxenergie/sunbase, pull requests merged in 2020-03, with the labels that each got.

#35 Feature/influxhelper
  README.md
  src/controllers/api-v1.ts
  src/controllers/home-controller.ts
  src/utils/InfluxHelper.ts
  views/home-page.squirrelly
Labels: enhancement

#31 Invalidate sessions after password change
  src/config/passport.ts
  src/controllers/profil-controller.ts
  src/models/Session.ts
  src/models/User.ts
Labels: help wanted, security

#37 Feature/admin deletion
  src/controllers/admin-controller.ts
  views/admin-page.squirrelly
Labels: bug, enhancement

#38 Async/await
  src/config/passport.ts
  src/controllers/api-v1.ts
  src/controllers/auth-controller.ts
  src/controllers/profil-controller.ts
Labels: enhancement

#39 Add a .editorconfig file and reformat project
  .editorconfig
  src/config/passport.ts
  src/config/session.ts
  src/controllers/admin-controller.ts
  src/controllers/api-v1.ts
  src/controllers/auth-controller.ts
  src/controllers/home-controller.ts
  src/controllers/profil-controller.ts
  src/db/influxdb.ts
  src/db/mongodb.ts
  src/models/Session.ts
  src/models/User.ts
  src/types/sqrl.d.ts
  src/utils/InfluxHelper.ts
  src/utils/logger.ts
  src/utils/route-auth.ts
Labels: meta

#40 Feature/chart
  src/app.ts
  src/controllers/home-controller.ts
  src/public/js/PCS-chart.js
  views/home-page.squirrelly
Labels: enhancement
