Repository boxenergie/sunbase, pull requests merged in 2020-02, with the labels that each got.

#30 Fix csurf acting on API
  src/app.ts
Labels: enhancement, security

#32 Refactor
  .env.example
  .gitignore
  .vscode/launch.json
  README.md
  example.env
  package-lock.json
  package.json
  scripts/licensify.sh
  src/app.ts
  src/config/helmet.ts
  src/config/passport.ts
  src/config/session.ts
  src/controllers/admin-controller.ts
  src/controllers/api-v1.ts
  src/controllers/auth-controller.ts
  src/controllers/home-controller.ts
  src/controllers/profil-controller.ts
  src/db/influxdb.ts
  src/db/mongodb.ts
  src/models/User.ts
  src/server.ts
  src/utils/logger.ts
  src/utils/route-auth.ts
  tsconfig.json
  views/admin-page.squirrelly
  views/home-page.squirrelly
  views/login-page.squirrelly
  views/profil-page.squirrelly
Labels: documentation, enhancement, security

#34 Create auto licensing action
  .github/workflows/license.yml
  scripts/licensify.sh
Labels: meta

#36 Add a Wind Influx table and its associated API
  src/app.ts
  src/controllers/api-v1.ts
  src/db/influxdb.ts
Labels: enhancement
