Repository boxenergie/sunbase, pull requests merged in 2020-01, with the labels that each got.

#13 API auth
  src/app.ts
  src/controllers/api-v1.ts
Labels: enhancement

#17 Second Sprint
  .gitignore
  README.md
  package.json
  src/InfluxDB/TableReleves.ts
  src/InfluxDB/Users.ts
  src/app.ts
  src/config/.gitkeep
  src/config/passport.ts
  src/controllers/api-v1.ts
  src/controllers/auth-controller.ts
  src/controllers/home-controller.ts
  src/controllers/profil-controller.ts
  src/db/influxdb.ts
  src/db/mongodb.ts
  src/db/sunshare_nodered_simulateur_modifie.json
  src/models/.gitkeep
  src/models/User.ts
  src/types/api.d.ts
  src/types/sqrl.d.ts
  src/utils/auth.ts
  views/homepage.squirrelly
  views/loginpage.squirrelly
  views/profilpage.squirrelly
Labels: minor

#26 License the software under AGPL
  COPYING
  licensify.sh
  scripts/cleanDist.ts
  scripts/copyStaticAssets.ts
  src/app.ts
  src/config/passport.ts
  src/controllers/api-v1.ts
  src/controllers/auth-controller.ts
  src/controllers/home-controller.ts
  src/controllers/profil-controller.ts
  src/db/influxdb.ts
  src/db/mongodb.ts
  src/models/User.ts
  src/public/css/main.css
  src/server.ts
  src/types/api.d.ts
  src/types/sqrl.d.ts
  src/utils/auth.ts
  views/homepage.squirrelly
Labels: meta

#27 Make the session persistent upon server shutdown
  package-lock.json
  package.json
  src/config/session.ts
Labels: enhancement

#22 Feature/node red
  README.md
  package.json
  src/db/sunshare_nodered_simulateur_modifie.json
  src/nodeRed/sunshare_nodered_bkp.txt
  src/nodeRed/sunshare_nodered_modifie.txt
Labels: enhancement, meta
